### ISSUE TITLE
Cura 5 marketplace

### ISSUE THREAD

**Issue by nfacha** [5axes/Calibration-Shapes#97]
Hello
I see an update for CUra 5 has been released (https://github.com/5axes/Calibration-Shapes/releases/tag/V2.0.0) although I cant find it on the marketplace, was the listing there updated?

**Comment by contagous** [comment]
curapackage works well for now, thanks

**Comment by 5axes** [comment]
Released in the market place

**Comment by 5axes** [comment]
This is normal, the version on the marketplace had a bug. So I proposed an update. But Ultimaker must validate this modification. Normally, if everything goes well, it takes 15 days to find again the plugin online. Otherwise there are always versions on here : https://github.com/5axes/Calibration-Shapes/releases/tag/V2.1.4
